import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/client/Header";
import { PromptContextProvider } from "@/context/PromptContext";
import { UserContext } from "@/context/UserContext";
import NeedToLoginSign from "@/client/NeedToLoginSign";

const geistSans = DM_Sans({
  // weight: ["100", "1000", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en" >
      <head>
        <script src="https://accounts.google.com/gsi/client" async defer></script>
        <script type="application/ld+json" dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": "Prompt Flow",
            "url": "https://promt-flow.space",
            "description": "A creative AI prompt generator built for developers and creators."
          })
        }} />
      </head>
      <body
        className={`${geistSans.className} antialiased`}
      >

        <UserContext>

          <PromptContextProvider>
            <Header />
            <>
              {children}
              <NeedToLoginSign />
              {modal}
            </>
          </PromptContextProvider>
        </UserContext>

      </body>
    </html>
  );
}
